# Generated by Django 2.0.5 on 2019-11-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ManyToManyField(to='hospital.Especialidad'),
        ),
    ]
